# credit goes to bitbrain for creating the action this is based on
# https://github.com/bitbrain/beehave/blob/godot-4.x/.github/actions/unit-test/action.yml
name: unit-test
description: "Runs the Godot unit tests using the GUT API"

inputs:
  godot-bin:
    required: true

runs:
  using: composite

  steps:
    - name: "Unit Test Linux"
      if: ${{ runner.OS == 'Linux' }}
      env:
        GODOT_BIN: "/home/runner/godot-linux/godot"
      shell: bash
      run: |
        $GODOT_BIN --headless --path . -s -d ./addons/gut/gut_cmdln.gd -gexit


# not tested yet
    - name: "Unit Test Windows cmd"
      if: ${{ runner.OS == 'Windows' }}
      env:
        GODOT_BIN: "C:\\Users\\runneradmin/godot-win/godot.exe"
      shell: cmd
      run: |
        echo "%HOMEPATH%"
        set unix_path=${{ inputs.godot-bin }}
        set win_path=%unix_path:~1%
        set win_path=%HOMEPATH%%unix_path:~1%
        set win_path=%win_path:/=\%
        echo "%win_path%"
        echo "%GODOT_BIN%"

        %GODOT_BIN% --headless -s -d .\addons\gut\gut_cmdln.gd -gexit

        
      #  chmod +x ./runtest.cmd
      #  ./runtest.cmd --continue
      #  set GODOT_BIN=%win_path%